repos:
- repo: https://github.com/python-poetry/poetry
  rev: '1.8.2'
  hooks:
  - id: poetry-check
  - id: poetry-lock
  - id: poetry-export
  - id: poetry-install

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.5
  hooks:
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      args: [ --fix ]
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
  - id: mypy
  files: ^src/
  additional_dependencies: [pandas-stubs, types-seaborn, types-requests]

- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.8.5
  hooks:
  - id: nbqa-mypy
    name: nbqa-mypy
    description: Run 'mypy' on a Jupyter Notebook
    entry: nbqa mypy
    language: python
    files: ^notebooks/
    require_serial: true
    types: [jupyter]
    additional_dependencies: [mypy, pandas-stubs, types-seaborn, types-requests]

- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes