FROM ny_tree_census_base

ARG UNAME=dockeruser
ARG UID=1001
ARG GID=1001
ARG REPO=AlekseiBogachev/ny-tree-census.git

USER root

COPY . /${UNAME}/ny_tree_census

RUN chown ${UNAME} -R /${UNAME}/ny_tree_census

USER $UNAME

WORKDIR /${UNAME}/ny_tree_census

RUN poetry install

RUN --mount=type=secret,id=pat,uid=${UID} \
git remote set-url origin https://$(cat /run/secrets/pat)@github.com/${REPO}

RUN poetry run pre-commit install --install-hooks --overwrite

CMD /bin/bash
