project:
  type: website

author: Aleksei Bogachev
date: 'September 3, 2024'

from: markdown+emoji

website:
  title: "NY Tree Census EDA"
  navbar:
    background: primary
    search: true
    tools:
    - icon: github
      href: https://github.com/AlekseiBogachev/ny-tree-census
    left:
      - href: index.qmd
        text: В начало
      - href: eda.qmd
        text: Исследовательский анализ данных
      - href: about.qmd
        text: О сайте

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    # toc-depth: 2
    code-fold: true
    code-summary: Show the code
    code-line-numbers: true
execute:
  enabled: true
jupyter: python3



