---
title: "NY Tree Census EDA"
---

Сайт посвящён [исследованию](eda.qmd) датасета
[2015 Street Tree Census - Tree Data](https://data.cityofnewyork.us/Environment/2015-Street-Tree-Census-Tree-Data/uvpi-gqnh/about_data)

::: {.callout-caution}
Проект и документация в стадии разработки.
:::

## 2015 Street Tree Census

Датасет содержит информацию о деревьях, растущих на улицах Нью-Йорка, собранную
в рамках проекта **2015 Street Tree Census** волонтёрами и сотрудниками
**NYC Parks & Recreation** и партнёрских организаций.

Собранные данные включают в себя информацию о видах деревьев, диаметре ствола и
оценку здоровья растения. Доступны сопроводительные данные, показывающие статус
сбора и публикации данных по всему городу.

[Подробнее о датасете можно узнать на его сайте.](https://data.cityofnewyork.us/Environment/2015-Street-Tree-Census-Tree-Data/uvpi-gqnh/about_data)

**Цель проекта** - выполнить исследовательский анализ данных и отработать
следующие приёмы:

- :heavy_check_mark: визуализация сложных данных,
- :heavy_check_mark: сборка Docker-образов,
- :heavy_check_mark: работа с CI/CD конвейерами,
- :heavy_check_mark: работа с документацией - сборка и публикация с `quarto` и **GitHub Pages**,
- :heavy_exclamation_mark: сборка и публикация артефактов исследования.

[Исследовательский анализ](eda.qmd) данных содержит следующие пункты:

- **превью данных** - таблица с небольшой выборкой из датасета,
- **оценка количества пропусков в столбцах** с помощью библиотеки
  [`missingno`](https://github.com/ResidentMario/missingno),
- **диаграмма попарного распределения признаков**,
- **матрица попарной корреляции между вещественными признаками**,
- **карта расположения деревьев** из датасета  
и другие разделы.
